### ISSUE TITLE
2° HW - esercizio uno

### ISSUE THREAD

**Issue by badasteroid** [diadiaOOP/DiaDiaRepo#4]
Implementare tutte le ristrutturazioni discusse nella

dispensa POO-08

• Scrivere quindi i test della classe ComandoVai

• Implementare le classi corrispondenti a tutti i comandi

previsti sino ad ora nel gioco

– «aiuto», «fine», «prendi», «posa»; «guarda»

– aggiungere la classe ComandoGuarda: «guarda» stampa le

informazioni sulla stanza corrente e sullo stato della partita

– aggiungere la classe ComandoNonValido

– scrivere i test per le classi ComandoPosa,

ComandoPrendi

N.B. bisogna rifattorizzare anche i vecchi test mantenendo sempre i test ed

il codice principale allineati

**Comment by AlekPiccio** [comment]
Mancano solo: la classe ComandoNonValido, i test su ComandoPosa e ComandoPrendi.

**Comment by badasteroid** [comment]
mancano solo i test su ComandoPosa e ComandoPrendi.
