### ISSUE TITLE
2° HW- esercizio due

### ISSUE THREAD

**Issue by badasteroid** [diadiaOOP/DiaDiaRepo#5]
Introdurre l'interfaccia FabbricaDiComandi

e la classe FabbricaDiComandiFisarmonica

Scrivere i test di unità su questa classe concreta

ma limitarsi alla sola verifica del corretto

riconoscimento dei comandi

– Suggerimento: per scrivere questi test, aggiungere i metodi

getNome() e getParametro() all'interfaccia Comando

– N.B.: evitare invece di soffermarsi sull'instanziamento della

corretta classe concreta associata a ciascun comando perché

ancora non abbiamo studiato gli strumenti più opportuni

per farlo correttamente
Il progetto sta crescendo: riorganizziamo

meglio le classi introducendo anche il package

– it.uniroma3.diadia.comandi

ove collocare i comandi e la fabbrica

**Comment by AlekPiccio** [comment]
finito
